import nodemailer from "nodemailer";
import { getAggregatedVentureReport } from "./reportAggregator.js";
import { buildVenturePdf } from "./pdfService.js";
import { projectMarkdown, sanitizeFilename } from "./exportService.js";

/**
 * Sends the completed Venture Blueprint (PDF and Markdown) to the specified email.
 * Gracefully handles unconfigured SMTP by returning a structured status.
 *
 * @param {string} projectId - Project ID
 * @param {string} userId - Authenticated user ID
 * @param {string} to - Recipient email address
 * @returns {Promise<Object>} Delivery result object
 */
export async function sendProjectEmail(projectId, userId, to) {
  // Check if SMTP is configured
  const smtpHost = process.env.SMTP_HOST ? process.env.SMTP_HOST.trim() : "";
  if (!smtpHost) {
    return {
      ok: false,
      sent: false,
      configured: false,
      message: "Email delivery is not configured. Set SMTP_HOST in server/.env to enable outbound delivery."
    };
  }

  // Aggregate project deliverables
  const report = await getAggregatedVentureReport(projectId, userId);
  const startupName = report.project.startupName;

  // Generate attachments
  const pdfBuffer = await buildVenturePdf(report);
  const mdContent = projectMarkdown(report);
  const mdBuffer = Buffer.from(mdContent, "utf-8");

  const pdfFilename = sanitizeFilename(startupName, "pdf");
  const mdFilename = sanitizeFilename(startupName, "md");

  const port = parseInt(process.env.SMTP_PORT, 10) || 587;
  const isSecure = port === 465;

  const transportOptions = {
    host: smtpHost,
    port,
    secure: isSecure
  };

  if (process.env.SMTP_USER && process.env.SMTP_PASS) {
    transportOptions.auth = {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS
    };
  }

  const transporter = nodemailer.createTransport(transportOptions);

  const fromAddress = process.env.SMTP_FROM || `"AI Venture Studio" <reports@localhost>`;

  const htmlBody = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b; line-height: 1.6;">
      <div style="border-bottom: 3px solid #0f766e; padding-bottom: 12px; margin-bottom: 20px;">
        <span style="font-size: 11px; font-weight: bold; color: #0f766e; letter-spacing: 1px; text-transform: uppercase;">AI Venture Studio Deliverable</span>
        <h1 style="font-size: 24px; margin: 6px 0 0; color: #0f172a;">${startupName} — Venture Blueprint</h1>
      </div>
      <p style="font-size: 14px; color: #475569;">
        Hello,
      </p>
      <p style="font-size: 14px; color: #334155;">
        Attached is your complete, investor-ready Venture Blueprint for <strong>${startupName}</strong>, generated by the AI Venture Studio autonomous engine.
      </p>
      <div style="background-color: #f0fdfa; border: 1px solid #99f6e4; border-radius: 8px; padding: 14px; margin: 20px 0;">
        <h3 style="margin: 0 0 6px; font-size: 13px; color: #0f766e; text-transform: uppercase;">Blueprint Summary</h3>
        <p style="margin: 0; font-size: 13px; color: #0f172a;">
          <strong>Startup Health Score:</strong> ${report.startupScore.overall} / 100<br>
          <strong>Readiness Rating:</strong> ${report.executiveSummary.readinessRating}<br>
          <strong>Completed Deliverables:</strong> ${report.metadata.completedDeliverables} of ${report.metadata.totalDeliverables}
        </p>
      </div>
      <p style="font-size: 13px; color: #64748b;">
        Attached Files:
      </p>
      <ul style="font-size: 13px; color: #334155;">
        <li><code>${pdfFilename}</code> (Full Investor-Ready Report PDF with Cover Page, Health Scorecard, and Deliverables)</li>
        <li><code>${mdFilename}</code> (Clean Markdown Source)</li>
      </ul>
      <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;" />
      <p style="font-size: 11px; color: #94a3b8;">
        Generated automatically by AI Venture Studio. Confidential.
      </p>
    </div>
  `;

  const info = await transporter.sendMail({
    from: fromAddress,
    to,
    subject: `Your Venture Blueprint: ${startupName} [AI Venture Studio]`,
    text: `Your venture blueprint for ${startupName} is attached.\n\nOverall Score: ${report.startupScore.overall}/100\nStatus: ${report.project.status}\n\nAttachments: ${pdfFilename}, ${mdFilename}`,
    html: htmlBody,
    attachments: [
      {
        filename: pdfFilename,
        content: pdfBuffer,
        contentType: "application/pdf"
      },
      {
        filename: mdFilename,
        content: mdBuffer,
        contentType: "text/markdown; charset=utf-8"
      }
    ]
  });

  return {
    ok: true,
    sent: true,
    configured: true,
    messageId: info.messageId,
    recipient: to,
    message: `Venture blueprint successfully delivered to ${to}`
  };
}

export default { sendProjectEmail };
